version: '3.5'

networks:
  postgres:
    driver: bridge

services:
  db:
    build:
      context: .
      dockerfile: ./t_db_dockerfile/Dockerfile
    container_name: postgres-db-app
##    ##command: createdb -U postgres homelibrarydb
    restart: always
    hostname: db.db.com
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - postgres
    healthcheck :
      test: [ "CMD", "pg_isready", "-q", "-d", "homelibrarydb", "-U", "postgres" ]
      interval : 10s
      timeout : 10s
      retries : 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    hostname: app.db.com
    restart: always
    ports:
      - '4000:4000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    networks:
      - postgres